/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { HookSpec, PanelSnapshot, WorktrunkRemoteResult } from 'dsh-worktrunk/contract'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$776f726b7472756e6b4d616e61676572 {
    copyIgnored: (input: { workspaceId: string; path?: string; force?: boolean; requireInclude?: boolean; }) => Promise<RemoteResult<WorktrunkRemoteResult<null>>>
    createWorktree: (input: { workspaceId: string; branch: string; base?: string; skipHooks?: boolean; }) => Promise<RemoteResult<WorktrunkRemoteResult<{ path: string; branch: string; hooksRan: boolean; registrationWarning?: string; }>>>
    ensureWorktreePermission: (input: { sessionId: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<{ status: string; preset?: string; }>>>
    mergeWorktree: (input: { workspaceId: string; branch: string; target?: string; keepCommit?: boolean; keepWorktree?: boolean; currentCwd?: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<null>>>
    openWorktree: (input: { workspaceId: string; path: string; branch: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<{ workspaceId?: string; }>>>
    previewHooks: (input: { workspaceId: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<readonly HookSpec[]>>>
    readPanel: (input: { workspaceId: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<PanelSnapshot>>>
    removeWorktree: (input: { workspaceId: string; branch: string; force?: boolean; forceDeleteBranch?: boolean; keepBranch?: boolean; currentCwd?: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<null>>>
  }
  interface TypertRemoteMap {
    'worktrunkManager/copyIgnored': (input: { workspaceId: string; path?: string; force?: boolean; requireInclude?: boolean; }) => Promise<RemoteResult<WorktrunkRemoteResult<null>>>
    'worktrunkManager/createWorktree': (input: { workspaceId: string; branch: string; base?: string; skipHooks?: boolean; }) => Promise<RemoteResult<WorktrunkRemoteResult<{ path: string; branch: string; hooksRan: boolean; registrationWarning?: string; }>>>
    'worktrunkManager/ensureWorktreePermission': (input: { sessionId: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<{ status: string; preset?: string; }>>>
    'worktrunkManager/mergeWorktree': (input: { workspaceId: string; branch: string; target?: string; keepCommit?: boolean; keepWorktree?: boolean; currentCwd?: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<null>>>
    'worktrunkManager/openWorktree': (input: { workspaceId: string; path: string; branch: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<{ workspaceId?: string; }>>>
    'worktrunkManager/previewHooks': (input: { workspaceId: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<readonly HookSpec[]>>>
    'worktrunkManager/readPanel': (input: { workspaceId: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<PanelSnapshot>>>
    'worktrunkManager/removeWorktree': (input: { workspaceId: string; branch: string; force?: boolean; forceDeleteBranch?: boolean; keepBranch?: boolean; currentCwd?: string; }) => Promise<RemoteResult<WorktrunkRemoteResult<null>>>
  }
  interface TypertRemoteNamespaceMap {
    'worktrunkManager': TypertRemoteNamespace$776f726b7472756e6b4d616e61676572
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
